image: python:3

.base_test:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  script:
    - make test

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - make lint

test-3.6:
  extends: .base_test
  image: python:3.6

test-3.7:
  extends: .base_test
  image: python:3.7

test-3.8-rc:
  extends: .base_test
  image: python:3.8-rc
